### ISSUE TITLE
SEP2: We should extend ADJUST() to work with argument types of xs:date and xs:time.

### ISSUE THREAD

**Issue by JervenBolleman** [w3c/sparql-12#109]
**Idea to improve SEP 2**

We should extend `ADJUST()` to work with argument types of xs:date and xs:time as well.

Adjust functions are described [here](https://www.w3.org/XML/Group/qtspecs/specifications/xpath-functions-31/html/Overview.html#timezone.functions)

**Comment by Tpt** [comment]
This operator is now in SEP 2. Could we close this issue?
