### ISSUE TITLE
Add Amazon Neptune to current implementors for SEP-0004

### ISSUE THREAD

**Issue by jaw111** [w3c/sparql-12#147]
**Idea to improve SEP-0004**

**Describe the improvement**
Amazon Neptune uses the graph name `http://aws.amazon.com/neptune/vocab/v01/DefaultNamedGraph` for the default graph.

**Additional context**
https://docs.aws.amazon.com/neptune/latest/userguide/feature-sparql-compliance.html#sparql-default-graph

**Comment by JervenBolleman** [comment]
Closed by #148
