### ISSUE TITLE
SPARQL 1.2 CG Charter

### ISSUE THREAD

**Issue by afs** [w3c/sparql-12#2]
Draft charter : https://w3c.github.io/sparql-12/charter.html

This issue is to agree on the initial charter for the CG.

**Comment by JervenBolleman** [comment]
Question in issue #3 regarding how commiter status is earned.

**Comment by pfps** [comment]
The draft charter says "new features".  I find that too limiting.  Why can't the group also consider changes and fixes to SPARQL 1.1?

**Comment by ajs6f** [comment]
I am no expert on W3C protocol, but my understanding is that we can do literally nothing with SPARQL 1.1. That Rec has been published, and it cannot be changed. What we can do is make suggestions towards 1.2, and 1.2 (think semantic versioning) must be backward-compatible with 1.1. Now, of course, there will be gray areas in the phrase "backward-compatible". There always are.

**Comment by afs** [comment]
It is being suggested that we use labelling and/or a section in the feature template to note the consequences, so categorisation of items would happen and we can have a range. 

This CG does not have exclusivity on providing input to W3C for any future SPARQL work. The charter text comes out of the scope text for the CG creation so it is what people have been signing up for.

(@ajs6f is right about W3C protocol.)

**Comment by dydra** [comment]
one goal of this effort should be to improve interoperability.
in that regard, i was surprised to see patel-schneider's
> I was hoping that this CG would look at  failures in the SPARQL 1.1 spec and come up with suggestions on how to solve them, but this doesn't appear to be part of the draft charter

but, upon reviewing the charter, i do not find any mention of attention to issues which impede interoperability.
bolleman' rephrasing as "features extending and correcting" suggests that this paragraph in the  charter could be extended a sentence which describes the intended approach to clarifications and corrections.

**Comment by pfpschneider** [comment]
Yes indeed, if the charter is expanded to include corrections then I would be satisfied.

**Comment by pfpschneider** [comment]
There is also the wording "special emphasis on features that leave existing SPARQL 1.1 queries and systems unchanged" that strongly indicates against allowing fixes of problems.

**Comment by dydra** [comment]
one would expect that, in those situations where undefined behaviour already undermines interoperability, that would be adequate reason to promote a definition.

**Comment by pfpschneider** [comment]
But the problems with EXISTS are not just undefined results, but in many cases completely wrong results, so you can't just lean on undefined to solve all ills.

**Comment by JervenBolleman** [comment]
For all, I have not commented on this yet to not bias the discussion to much
@pfpschneider This is my personal opinion. For the Exist issues there is an existing community group chartered for exactly that topic. So per "spec" of community groups we shouldn't take that over. Community groups are different than working groups as in they are collections of people and organizations whom want to collectively work on a topic, much less formal than W3C working groups. Taking into account there seems to be slow but consistent progress in that CG so it is not dormant. The issues with Exist are therefore best left in their capable hands, with this CG liaising with the EXISTS CG if needed (considering shared chairs that should not be hard).

Generally on the second topic of backwards compatibility. Our community seems to want to improve adoption of SPARQL and RDF. Breaking peoples code that works today is unlikely to be construed as an improvement. i.e. more like the Java 6->7->8 changes than Scala recompile the world every 6 weeks ;)
In that way I join the view of @ajs6f in being extremely reluctant to introduce breaking any backwards compatibility into the charter. This means to me that collecting Errata are in scope (#68) (as they are mostly clarifications), renaming `where` to `match` would not be.

**Comment by pfps** [comment]
The SPARQL exists community group is not only dormant, it is comatose or dead.  The last non-administrative posts to the group's mailing list are from February 2018.  The last change to any draft document for the group is from April 2017.  The group has not published any documents.  There never was any consensus in the group as to what to do with EXISTS. Claiming that the group is making progress of any kind is not correct.

**Comment by TallTed** [comment]
All -- We have URIs for things like CGs for good reason.  Please use them when relevant.

* [The "SPARQL Maintenance (EXISTS)" Community Group](https://www.w3.org/community/sparql-exists/)
  * [public (primary) mailing list](https://lists.w3.org/Archives/Public/public-sparql-exists/)
  * [github repo](https://github.com/w3c/sparql-exists)
  * [DRAFT CG Report: "SPARQL EXISTS errata"](https://w3c.github.io/sparql-exists/docs/sparql-exists.html)
  * [tests](https://github.com/w3c/sparql-exists/tree/gh-pages/tests)
  * [issues list](https://github.com/w3c/sparql-exists/issues)

**Comment by TallTed** [comment]
@pfps - The appropriate place for critique of EXISTS CG work is that group's [issues list](https://github.com/w3c/sparql-exists/issues) and/or [mailing list](https://lists.w3.org/Archives/Public/public-sparql-exists/).

I see no open (nor closed) issues on the former, and the last thread on the latter ended with a comment to you, to which you did not reply.  I believe these would lead most people to conclude that all concerns raised had been resolved.

**Comment by TallTed** [comment]
@JervenBolleman - The above notwithstanding, I think it would be entirely reasonable for the [EXISTS CG](https://www.w3.org/community/sparql-exists/) (as a group specifically focused on a single SPARQL 1.1 error/omission/however-you-want-to-characterize-it) to hand [their report](https://w3c.github.io/sparql-exists/docs/sparql-exists.html) (whether still considered DRAFT or not) to the [SPARQL 1.2 CG](https://www.w3.org/community/sparql-12/) (as a group specifically focused on revising the [SPARQL 1.1 spec](https://www.w3.org/TR/sparql11-overview/) as a whole).

**Comment by afs** [comment]
I have suggested to the Exists CG to publish the material it has in a neutral way - the issues identified and the two solutions. This is progress even if not a single, agreed proposal.

https://lists.w3.org/Archives/Public/public-sparql-exists/2019Apr/0001.html

**Comment by pfps** [comment]
The email mentioned by dydra on April 3, 2019, is https://lists.w3.org/Archives/Public/public-sparql-12/2019Apr/0029.html

**Comment by JervenBolleman** [comment]
The vote is open on issue #75 closing this issue as it was not clear this was a vote for acceptance.
