### ISSUE TITLE
standardization of communicating partial results

### ISSUE THREAD

**Issue by joernhees** [w3c/sparql-12#35]

**Comment by cygri** [comment]
Is this about blank nodes?

**Comment by afs** [comment]
@joernhees  Could you provide a description please?

I read this as being about when a query is only partially completed e.g. a query timeout means the results are cut off. It's not an HTTP error - the HTTP request is being executed correctly.

(Even if there is an HTTP error to send, the server has to buffer the results to be able to send the HTTP status code out first which is a significant impact on the server.)

**Comment by RickMoynihan** [comment]
@afs I read the issue as being this too, and have literally just written this up here: https://github.com/w3c/sparql-12/issues/8#issuecomment-479644907

**Comment by VladimirAlexiev** [comment]
@joernhees has us all guessing, but perhaps this is also related to #49

**Comment by joernhees** [comment]
sorry, i only just saw this... i thought the issue was lost due to connection interrupt... #51 is the correct one, yes.
