### ISSUE TITLE
Vote for charter.html acceptance at 5d2a2a9

### ISSUE THREAD

**Issue by JervenBolleman** [w3c/sparql-12#75]
Please vote by using the reaction option. 
* Thumbs up: means vote for
* Thumbs down : means vote against
* Any other reaction or comment will be ignored
* We should not have comments on this issue itself
* This vote will run until 2nd of May 2019 23:59 UTC

You need to be part of the community group to participate and only votes with the github account linked to your CG profile will be counted.

The charter can be read at (https://w3c.github.io/sparql-12/charter.html) or in the raw version at (https://github.com/w3c/sparql-12/blob/5d2a2a941bc27e5fc5689951779beafd0ff1e35c/docs/charter.html)

**Comment by azaroth42** [comment]
Community groups can produce specifications, just not W3C blessed technical reports. For example, the Open Annotation CG produced a specification that was implemented by many and then adopted as the baseline for the Web Annotation Data Model. The JSON-LD WG produced specifications that were adopted in the WG almost wholesale. Plus many more.

I think the charter should say that a SPARQL 1.2 specification will be a deliverable, intended as the input to a WG with SPARQL in its scope in the future. The trend in the W3C towards incubation in CGs is quite strong, and just white papers aren't sufficient demonstration of importance and adoption.

So I'm :-1: as I feel the charter does not go far enough, but this is not the equivalent of a formal objection.

**Comment by afs** [comment]
Comment discussion on the mailing list: [2019Apr/0052](https://lists.w3.org/Archives/Public/public-sparql-12/2019Apr/0052.html).

**Comment by rubensworks** [comment]
For reference, some minor comments on the charter that should have no impact on the vote (I can PR these after the vote):

> Out of Scope
Changes to the W3C Recommendations.

I would change this to "Non-backwards compatible changes to the W3C Recommendations".
Perhaps a concrete definition of what "non-backwards compatibility" means in this context would be useful.

> Dependencies or Liaisons

I assume the EXISTS CG should be added here as well?

**Comment by dbooth-boston** [comment]
Do people really want the charter to be this rigid about backward compatibility?  As a case in point, issue #77 (Problems with numeric character escapes) seems like an excellent candidate for consideration, but it would not be a backward compatible change.

**Comment by kasei** [comment]
I think #77 is a good example of something we should consider. It would not be backwards compatible, but there’s strong evidence that no one implements the spec as written anyway, so it’s not clear what value backwards compatibility provides here.

**Comment by TallTed** [comment]
I think this pointer to the mailing list conversation --

> Comment discussion on the mailing list: [2019Apr/0052](https://lists.w3.org/Archives/Public/public-sparql-12/2019Apr/0052.html).

-- should be in the top-post of this issue.  There are clearly a number of things worthy of comment, which don't currently have a good outlet.

To be clear about my own vote here -- I am in favor of this as an initial CG Charter, revision of which has a *much* lower hurdle than charter revision for either an old-style XG or a current WG, in order to get and keep these wheels rolling.

That said, I do not think the current draft charter is optimal, and am concerned that "no conflict with existing SPARQL 1.1 or 1.0 specs" (or is that "no disruption of existing SPARQL 1.1 or 1.0 tools", which has a rather different meaning in the end, particularly considering #77) may result in enshrining as permanent things which are *far* from worthy of that permanence.  To put it simply -- bugs happen!

**Comment by kasei** [comment]
@afs @JervenBolleman Any thoughts from the chairs about backwards compatibility (especially with respect to issues such as #77)? I'm hesitant about the charter wording regarding "Changes to the W3C Recommendations."

**Comment by afs** [comment]
I think each needs to make its own case. Writing a charter that includes open scope to rewrite SPARQL would be a different CG.

[public-sparql-12/2019Apr/0061](https://lists.w3.org/Archives/Public/public-sparql-12/2019Apr/0061.html)

Specifically to "Changes to the W3C Recommendations" - that is slightly different. Some people expected changes in-place to the SPARQL 1.1 Recs. The "out of scope" statement is motivated by being clear we can't do that.

**Comment by JervenBolleman** [comment]
The vote is closed with +17 and -1, charter is accept as is for now.

I understand not everyone is pleased by the way this charter is. 
However, I hope that the work we will do together will be pleasing for everyone.
The work is important the charter not.

In the coming month (June) I will collect spelling and typo changes and merge them using the simple decision process.
